### ISSUE TITLE
Please update to highcharts@4.1.7

### ISSUE THREAD

**Issue by davidamh** [crealogix/highcharts-commonjs#1]
My team is running into a bug (https://github.com/highslide-software/highcharts.com/issues/4284) that was fixed in highcharts version 4.1.7, published on June 26. We would greatly appreciate it if you could update this repo to mirror version 4.1.7.

Thanks!
David Hernandez

**Comment by davidagraf** [comment]
Version 4.1.7-1 is published. Please check.
